name: wanheng_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.8+22

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_facebook_auth: ^6.0.0 
  table_calendar: ^3.0.9
  intl: ^0.18.0
  # smooth_compass: ^2.0.4
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.5
  dio: ^5.1.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.1.0
  dropdown_button2: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.7+4 
  pin_code_fields: ^7.4.0
  permission_handler: ^10.2.0
  # flutter_compass: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  convex_bottom_bar: ^3.2.0
  font_awesome_flutter: ^10.4.0
  purchases_flutter: ^5.2.1
  google_sign_in: ^6.1.4
  lat_compass: ^1.0.4+1
  url_launcher: ^6.1.11
  sign_in_with_apple: ^5.0.0
  jwt_decoder: ^2.0.1
  camera: ^0.10.5+4
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  # flutter_sensors: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/noimage.jpg
    - assets/images/compass.png
    - assets/images/bgcompass.png
    - assets/images/arrow.png
    - assets/images/checked.png

    - assets/images/logo_google.png
    
    - assets/images/bg/bg1.png
    - assets/images/bg/bg2.png
    - assets/images/bg/bg3.png
    - assets/images/bg/bg4.png
    - assets/images/bg/loading.jpg

    - assets/images/bg/bg_card_detail.png

    - assets/images/element/0_element_fire.png
    - assets/images/element/0_element_gold.png
    - assets/images/element/0_element_soli.png
    - assets/images/element/0_element_water.png
    - assets/images/element/0_element_wood.png
    - assets/images/element/1_element_fire.png
    - assets/images/element/1_element_gold.png
    - assets/images/element/1_element_soli.png
    - assets/images/element/1_element_water.png
    - assets/images/element/1_element_wood.png

    - assets/images/horo/0_cock.png
    - assets/images/horo/0_dog.png
    - assets/images/horo/0_goat.png
    - assets/images/horo/0_great_snake.png
    - assets/images/horo/0_horse.png
    - assets/images/horo/0_monkey.png
    - assets/images/horo/0_ox.png
    - assets/images/horo/0_pig.png
    - assets/images/horo/0_rabbit.png
    - assets/images/horo/0_rat.png
    - assets/images/horo/0_snake.png
    - assets/images/horo/0_tiger.png
    - assets/images/horo/1_cock.png
    - assets/images/horo/1_dog.png
    - assets/images/horo/1_goat.png
    - assets/images/horo/1_great_snake.png
    - assets/images/horo/1_horse.png
    - assets/images/horo/1_money.png
    - assets/images/horo/1_ox.png
    - assets/images/horo/1_pig.png
    - assets/images/horo/1_rabbit.png
    - assets/images/horo/1_rat.png
    - assets/images/horo/1_snake.png
    - assets/images/horo/1_tiger.png
    - assets/images/icons/0fire.png
    - assets/images/icons/0gold.png
    - assets/images/icons/0soli.png
    - assets/images/icons/0water.png
    - assets/images/icons/0wood.png
    - assets/images/icons/1fire.png
    - assets/images/icons/1gold.png
    - assets/images/icons/1soli.png
    - assets/images/icons/1water.png
    - assets/images/icons/1wood.png
    - assets/images/icons/arrow_up.png
    - assets/images/icons/diadem.png
    

 
  fonts:
  - family: kanit
    fonts:
      - asset: assets/fonts/Kanit-Regular.ttf
      - asset: assets/fonts/Kanit-Bold.ttf
  - family: Prompt
    fonts:
      - asset: assets/fonts/Prompt-Regular.ttf
